name: fitness
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - conda-forge::r-base=4.2.2
  - conda-forge::r-tidyverse=1.3.2
  - bioconda::bioconductor-deseq2=1.42.0
  - bioconda::bioconductor-biocparallel=1.36.0
  - bioconda::bioconductor-limma=3.58.1"
